### ISSUE TITLE
hi，I have some doubts about the ```fli``` instruction.

### ISSUE THREAD

**Issue by jinma-work** [a4lg/binutils-gdb#106]
hi，I have some doubts about the ```fli``` instruction.
I'm not sure. If the number 0-31 is used instead of the table "Immediate values loaded by the FLI.S instruction", how can this reflect the actual floating point of the load at the instruction level? Is it more appropriate to use ```fli.h ft1, -1.0``` instead of ```fli.h ft1, 0```?

_Originally posted by @jinma-work in https://github.com/a4lg/binutils-gdb/pull/56#discussion_r1052944126_

**Comment by a4lg** [comment]
As I explained earlier, this is not the right place to talk about this (since it only implements draft specification of [riscv/riscv-isa-manual](https://github.com/riscv/riscv-isa-manual)).  After the `Zfa` extension is changed, I will consider changing it.
